export {default as profile1} from "./Sree-profile.png"
// export {default as profile2} from "./profile-2.jpg"
export {default as profile2} from "./Sree-profile.png"
export {default as profile3} from "./edulyn.png"
export {default as MyResume} from "./Srikanth Merugu Resume.pdf"
export {default as NewLogo} from "./New-Log0.png"
export {default as matchoo} from  "./matchoo.png"
export {default as Smartuter} from  "./Smartuter.png"
export {default as Vetoro} from  "./Vetoro.png"
export {default as juice} from './juice.png'